# OpenTelemetry Java Agent 다운로드를 위한 ConfigMap
# InitContainer에서 사용될 다운로드 스크립트
apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-java-agent-script
  namespace: tamnara-prod
data:
  download-agent.sh: |
    #!/bin/bash
    AGENT_VERSION="1.32.0"
    DOWNLOAD_URL="https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v${AGENT_VERSION}/aws-opentelemetry-agent.jar"
    
    echo "Downloading OpenTelemetry Java Agent version ${AGENT_VERSION}..."
    wget -O /shared/aws-opentelemetry-agent.jar "${DOWNLOAD_URL}"
    
    if [ $? -eq 0 ]; then
      echo "Successfully downloaded OpenTelemetry Java Agent"
      ls -la /shared/aws-opentelemetry-agent.jar
    else
      echo "Failed to download OpenTelemetry Java Agent"
      exit 1
    fi 