apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-config.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - hpa-backup.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml
