apiVersion: v1
kind: Service
metadata:
  name: tamnara-backend-service
  namespace: tamnara-prod
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 