apiVersion: v1
kind: Service
metadata:
  name: tamnara-backend-service
  namespace: tamnara-prod
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: management
    port: 9292
    targetPort: 9292
    protocol: TCP
  type: ClusterIP 