apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: backend
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/18-team-timeline-cloud.git
    targetRevision: main
    path: argocd/manifests/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 