apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: argocd-image-updater=quay.io/argoproj/argocd-image-updater
    argocd-image-updater.argoproj.io/argocd-image-updater.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/18-team-timeline-cloud.git
    targetRevision: main
    path: argocd/manifests/image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 10 