apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.14.0
    helm:
      values: |
        operator:
          replicaCount: 1
        metricsServer:
          replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 